import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faAnchor,
  faAnkh,
  faBiohazard,
  faBinoculars,
  faGolfBall,
  faBowlingBall,
  faBaseballBall,
  faFootballBall,
  faBasketballBall,
  faVolleyballBall,
  faBell,
  faBrain,
  faBurn,
  faCat,
  faCircle,
  faCog,
  faCogs,
  faDog,
} from '@fortawesome/free-solid-svg-icons'

export let loadIcons = [
  faAnchor,
  faAnkh,
  faBiohazard,
  faBinoculars,
  faGolfBall,
  faBowlingBall,
  faBaseballBall,
  faFootballBall,
  faBasketballBall,
  faVolleyballBall,
  faBell,
  faBrain,
  faBurn,
  faCat,
  faCircle,
  faCog,
  faCogs,
  faDog,
]
